/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbc;

import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Group D
 * @author Ille Buturas
 * @author Vasil Dzhakov
 * @author Keith Reyes
 */
public class LoginRegPanel extends javax.swing.JFrame {
    /**
     * Creates new form AuthGui
     */
    public LoginRegPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        TopPanel = new javax.swing.JPanel();
        LogoPanel = new javax.swing.JPanel();
        LogoText = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        LogInPanel = new javax.swing.JPanel();
        Email = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        LoginTitle = new javax.swing.JLabel();
        TitleText = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        LoginBtn = new javax.swing.JButton();
        SignUpPanel = new javax.swing.JPanel();
        RegisterBtn = new javax.swing.JButton();
        SignupTitle = new javax.swing.JLabel();
        SignupText = new javax.swing.JLabel();
        UsernameLb = new javax.swing.JLabel();
        rUsername = new javax.swing.JTextField();
        FirstNamelb = new javax.swing.JLabel();
        rFirstName = new javax.swing.JTextField();
        LastNameLb = new javax.swing.JLabel();
        rLastName = new javax.swing.JTextField();
        EmailLb = new javax.swing.JLabel();
        rEmail = new javax.swing.JTextField();
        PasswordLb = new javax.swing.JLabel();
        ConfirmPasswordLb = new javax.swing.JLabel();
        rPassword = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        ClearBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 211, 19));

        TopPanel.setBackground(new java.awt.Color(255, 219, 11));
        TopPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TopPanel.setForeground(new java.awt.Color(255, 219, 187));

        LogoPanel.setBackground(new java.awt.Color(255, 219, 11));
        LogoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        LogoText.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        LogoText.setText("Traffic Data Visualization");

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbc/traffix_logo_v1.png"))); // NOI18N
        Logo.setText("jLabel5");

        javax.swing.GroupLayout LogoPanelLayout = new javax.swing.GroupLayout(LogoPanel);
        LogoPanel.setLayout(LogoPanelLayout);
        LogoPanelLayout.setHorizontalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoPanelLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoPanelLayout.createSequentialGroup()
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoPanelLayout.createSequentialGroup()
                        .addComponent(LogoText)
                        .addGap(90, 90, 90))))
        );
        LogoPanelLayout.setVerticalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogoText)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        LogInPanel.setBackground(new java.awt.Color(255, 226, 40));
        LogInPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Email.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Email.setText("Email");

        email.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        Password.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Password.setText("Password");

        LoginTitle.setFont(new java.awt.Font("Century Gothic", 1, 39)); // NOI18N
        LoginTitle.setText("Log in");

        TitleText.setText("Log in to existing account");

        password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        LoginBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LogInPanelLayout = new javax.swing.GroupLayout(LogInPanel);
        LogInPanel.setLayout(LogInPanelLayout);
        LogInPanelLayout.setHorizontalGroup(
            LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogInPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Email)
                            .addComponent(Password)
                            .addComponent(email)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(LogInPanelLayout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(LoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(TitleText)
                    .addComponent(LoginTitle))
                .addGap(74, 74, 74))
        );
        LogInPanelLayout.setVerticalGroup(
            LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogInPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LoginTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TitleText)
                .addGap(35, 35, 35)
                .addComponent(Email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(LoginBtn)
                .addGap(172, 172, 172))
        );

        SignUpPanel.setBackground(new java.awt.Color(255, 226, 40));
        SignUpPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.darkGray, null, null));

        RegisterBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        RegisterBtn.setText("Register");
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });

        SignupTitle.setFont(new java.awt.Font("Century Gothic", 1, 39)); // NOI18N
        SignupTitle.setText("Sign Up");

        SignupText.setText("Register a new account");

        UsernameLb.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        UsernameLb.setText("Username");

        rUsername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        rUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rUsernameActionPerformed(evt);
            }
        });

        FirstNamelb.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        FirstNamelb.setText("First name");

        rFirstName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        LastNameLb.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LastNameLb.setText("Last name");

        rLastName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        EmailLb.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EmailLb.setText("Email");

        rEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        PasswordLb.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        PasswordLb.setText("Password");

        ConfirmPasswordLb.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ConfirmPasswordLb.setText("Confirm password");

        rPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPasswordField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ClearBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ClearBtn.setText("Clear Form");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SignUpPanelLayout = new javax.swing.GroupLayout(SignUpPanel);
        SignUpPanel.setLayout(SignUpPanelLayout);
        SignUpPanelLayout.setHorizontalGroup(
            SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SignupText)
                    .addComponent(SignupTitle)
                    .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(SignUpPanelLayout.createSequentialGroup()
                            .addComponent(RegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ClearBtn))
                        .addComponent(PasswordLb, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EmailLb, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rEmail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LastNameLb, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rLastName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(FirstNamelb, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(UsernameLb, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rUsername, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ConfirmPasswordLb, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rPassword, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        SignUpPanelLayout.setVerticalGroup(
            SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignUpPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(SignupTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignupText)
                .addGap(31, 31, 31)
                .addComponent(UsernameLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FirstNamelb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LastNameLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmailLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConfirmPasswordLb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(SignUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearBtn)
                    .addComponent(RegisterBtn))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel1.setText("©traffix, 2021 - 115 New Cavendish Street, London, W1W 6UW, UK");

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogInPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignUpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(133, 133, 133))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SignUpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LogInPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        
        String rusername = rUsername.getText();
        String flag = "no";
        String rfname = rFirstName.getText();
        String rlname = rLastName.getText();
        String remail = rEmail.getText();
        String pwd1 = rPassword.getText();
        String pwd2 = jPasswordField2.getText();
        //get email and username from database
        ResultSet emailResultSet = registeredUserTable.get(remail);
        ResultSet usernameResultSet = registeredUserTable.getUsername(rusername);
        //check if email in correct format
        String emailRegex = "^[_a-z0-9-]+(\\.[a-z0-9-]+)*@[a-z0-9-]+(\\.[a-z0-9-]+)*(\\.[a-z]{2,3})$";

        try {
            if (rusername.equals("") || rfname.equals("") || rlname.equals("") || remail.equals("") || pwd1.equals("") || pwd2.equals("")) {
                JOptionPane.showMessageDialog(this, "Please fill out all fields!");
            } else if (usernameResultSet.next()) {
                JOptionPane.showMessageDialog(this, "This username is already registered!");
            } else if (emailResultSet.next()) {
                JOptionPane.showMessageDialog(this, "This email is already registered!");
            } else if (!remail.matches(emailRegex)) {
                JOptionPane.showMessageDialog(this, "Email not in valid format!");
            } else if (!pwd1.equals(pwd2)) {
                JOptionPane.showMessageDialog(this, "Passwords do not match!");
            } else {
                //add user to database (from registeredUserTable)
                registeredUserTable.insert(rusername, flag, rfname, rlname, remail, pwd1);

                JOptionPane.showMessageDialog(this, "You have been registered successfully.");

                rUsername.setText("");
                rFirstName.setText("");
                rLastName.setText("");
                rEmail.setText("");
                rPassword.setText("");
                jPasswordField2.setText("");
            }
        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
        }


    }//GEN-LAST:event_RegisterBtnActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        
        String uemail = email.getText();
        String upassword = password.getText();
        ResultSet emailResultSet = registeredUserTable.get(uemail);
        ResultSet passwordResultSet = registeredUserTable.getPassword(upassword);
        String username = getUsername(uemail);
        try {
            if (uemail.equals("") || upassword.equals("")) {
                JOptionPane.showMessageDialog(this, "Please fill out all fields!");
            } else if (!emailResultSet.next()) {
                JOptionPane.showMessageDialog(this, "This email is not recognised!");
            } else if (!passwordResultSet.next()) {
                JOptionPane.showMessageDialog(this, "Incorrect password!");
            } else {
                addLoginStamp(username);
                AccountScreen accPanel = new AccountScreen(uemail);
                accPanel.setLocationRelativeTo(null);
                accPanel.setVisible(true);
                this.setVisible(false);
                this.dispose();
            }
        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void KeepSignedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeepSignedInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KeepSignedInActionPerformed

    private void TermsCondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TermsCondActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TermsCondActionPerformed

    private void rUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rUsernameActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed

        rUsername.setText("");
        rFirstName.setText("");
        rLastName.setText("");
        rEmail.setText("");
        rPassword.setText("");
        jPasswordField2.setText("");
    }//GEN-LAST:event_ClearBtnActionPerformed
    
    private void addLoginStamp(String username) {
            Connection con = connectUsersDB.getConnection();
            Statement stmt = null;
            
            // get date/time
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
            LocalDateTime now = LocalDateTime.now();
            
            String sql1 = ("SELECT username FROM Activity WHERE username = '" + username + "'");
            String sql2 = ("UPDATE Activity SET loginTime='"+ dtf.format(now) + "'," + "logoutTime='Logged in...' WHERE username='" + username + "';");
            String sql3 = ("INSERT OR IGNORE INTO Activity(username,loginTime,logoutTime) "
                    + "VALUES ('" + username + "','" + dtf.format(now) + "','" + "Logged in..." + "');");
            try {
                con.setAutoCommit(false);
                stmt = con.createStatement();
                ResultSet check = stmt.executeQuery(sql1);
                System.out.println(check);
                if(check.next()){
                    stmt.executeUpdate(sql2);
                    System.out.println("Updated login timestamp to database Activity!");
                }else{
                    stmt.executeUpdate(sql3);
                    System.out.println("Inserted login timestamp to database Activity!");
                }
                stmt.close();
                con.commit();
            } catch (SQLException ex) {
                System.err.println("SQLException: " + ex.getMessage());
            } finally {
                if (stmt != null) {
                    try {
                        stmt.close();
                    } catch (SQLException e) {
                        System.err.println("SQLException: " + e.getMessage());
                    }
                }
                if (con != null) {
                    try {
                        con.close();
                    } catch (SQLException e) {
                        System.err.println("SQLException: " + e.getMessage());
                    }
                }
            }
        }
    private String getUsername(String email) {
        Connection conn = connectUsersDB.getConnection();
        String sql = "SELECT username FROM Users WHERE email = '" + email + "'";
        ResultSet result = null;
        String username;
        try {
            Statement statement = conn.createStatement();
            result = statement.executeQuery(sql);
            
            username = result.getString("username");
            conn.close();
            return username;
        } catch (SQLException e) {
            System.out.println("Error while getting from Users table" + e.getMessage());
            return null;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginRegPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginRegPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginRegPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginRegPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginRegPanel().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearBtn;
    private javax.swing.JLabel ConfirmPasswordLb;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel EmailLb;
    private javax.swing.JLabel FirstNamelb;
    private javax.swing.JLabel LastNameLb;
    private javax.swing.JPanel LogInPanel;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JLabel LoginTitle;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel LogoPanel;
    private javax.swing.JLabel LogoText;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel PasswordLb;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JPanel SignUpPanel;
    private javax.swing.JLabel SignupText;
    private javax.swing.JLabel SignupTitle;
    private javax.swing.JLabel TitleText;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JLabel UsernameLb;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField rEmail;
    private javax.swing.JTextField rFirstName;
    private javax.swing.JTextField rLastName;
    private javax.swing.JPasswordField rPassword;
    private javax.swing.JTextField rUsername;
    // End of variables declaration//GEN-END:variables
}
