/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbc;

/**
 *
 * @author alexbuturas
 */
public class Start_Panel extends javax.swing.JFrame {

    /**
     * Creates new form Start_Panel
     */
    public Start_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainP = new javax.swing.JPanel();
        registrationP = new javax.swing.JPanel();
        singpLabel = new javax.swing.JLabel();
        newAccLabel = new javax.swing.JLabel();
        unameLabel = new javax.swing.JLabel();
        fNameLabel = new javax.swing.JLabel();
        lNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        confpwdLabel = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        fName = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        lName = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        condpwd = new javax.swing.JPasswordField();
        termsCond = new javax.swing.JCheckBox();
        signupB = new javax.swing.JButton();
        logoP = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        trafficDataLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        loginP = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        userEmailLabel = new javax.swing.JLabel();
        userPwdLabel = new javax.swing.JLabel();
        userEmail = new javax.swing.JTextField();
        userPwd = new javax.swing.JPasswordField();
        showPwd = new javax.swing.JCheckBox();
        keepSigned = new javax.swing.JCheckBox();
        loginB = new javax.swing.JButton();
        existAccLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("traffix");
        setResizable(false);

        mainP.setBackground(new java.awt.Color(255, 219, 11));

        registrationP.setBackground(new java.awt.Color(255, 226, 39));
        registrationP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        singpLabel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        singpLabel.setText("Sign up");

        newAccLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        newAccLabel.setText("Register with a new account.");

        unameLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        unameLabel.setText("Username:");

        fNameLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        fNameLabel.setText("First Name:");

        lNameLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        lNameLabel.setText("Last Name:");

        emailLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        emailLabel.setText("Email:");

        passwordLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        passwordLabel.setText("Password:");

        confpwdLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        confpwdLabel.setText("Confirm Password:");
        confpwdLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        username.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        username.setOpaque(true);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        fName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fName.setOpaque(true);
        fName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameActionPerformed(evt);
            }
        });

        email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        email.setOpaque(true);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        lName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lName.setOpaque(true);
        lName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameActionPerformed(evt);
            }
        });

        password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        password.setOpaque(true);

        condpwd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        condpwd.setOpaque(true);

        termsCond.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        termsCond.setText("I agree with the Terms and Conditions.");

        signupB.setBackground(new java.awt.Color(0, 0, 0));
        signupB.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        signupB.setForeground(new java.awt.Color(255, 255, 255));
        signupB.setText("Sign up");
        signupB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        signupB.setBorderPainted(false);
        signupB.setFocusable(false);
        signupB.setName(""); // NOI18N
        signupB.setOpaque(true);
        signupB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registrationPLayout = new javax.swing.GroupLayout(registrationP);
        registrationP.setLayout(registrationPLayout);
        registrationPLayout.setHorizontalGroup(
            registrationPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(registrationPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrationPLayout.createSequentialGroup()
                        .addGroup(registrationPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registrationPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(registrationPLayout.createSequentialGroup()
                                    .addComponent(emailLabel)
                                    .addGap(36, 36, 36))
                                .addComponent(fNameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(unameLabel))
                        .addGroup(registrationPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registrationPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(registrationPLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(registrationPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(password)))))
                    .addGroup(registrationPLayout.createSequentialGroup()
                        .addGroup(registrationPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNameLabel)
                            .addComponent(passwordLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(registrationPLayout.createSequentialGroup()
                        .addComponent(confpwdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(condpwd)))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(singpLabel)
                .addGap(156, 156, 156))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(registrationPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPLayout.createSequentialGroup()
                        .addComponent(termsCond)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPLayout.createSequentialGroup()
                        .addComponent(newAccLabel)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPLayout.createSequentialGroup()
                        .addComponent(signupB, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))))
        );
        registrationPLayout.setVerticalGroup(
            registrationPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationPLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(singpLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newAccLabel)
                .addGap(35, 35, 35)
                .addGroup(registrationPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unameLabel))
                .addGap(25, 25, 25)
                .addGroup(registrationPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameLabel)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(registrationPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNameLabel)
                    .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(registrationPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(registrationPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(registrationPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confpwdLabel)
                    .addComponent(condpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(termsCond)
                .addGap(18, 18, 18)
                .addComponent(signupB, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        logoP.setBackground(new java.awt.Color(255, 219, 11));
        logoP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        logo.setBackground(new java.awt.Color(255, 255, 128));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/traffix_logo_v1.png"))); // NOI18N

        trafficDataLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        trafficDataLabel.setText("Traffic Data Visualisation");

        javax.swing.GroupLayout logoPLayout = new javax.swing.GroupLayout(logoP);
        logoP.setLayout(logoPLayout);
        logoPLayout.setHorizontalGroup(
            logoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(logoPLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(trafficDataLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoPLayout.setVerticalGroup(
            logoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trafficDataLabel)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        infoLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        infoLabel.setText("© traffix, 2021 - 115 New Cavendish Street, London, W1W 6UW, UK Tel: +442079115000");

        loginP.setBackground(new java.awt.Color(255, 226, 39));
        loginP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        loginLabel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        loginLabel.setText("Log in");

        userEmailLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        userEmailLabel.setText("Email:");

        userPwdLabel.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        userPwdLabel.setText("Password:");

        userEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        userEmail.setOpaque(true);
        userEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEmailActionPerformed(evt);
            }
        });

        userPwd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        userPwd.setOpaque(true);

        showPwd.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        showPwd.setText("Show Password");
        showPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPwdActionPerformed(evt);
            }
        });

        keepSigned.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        keepSigned.setText("Keep Signed In");

        loginB.setBackground(new java.awt.Color(0, 0, 0));
        loginB.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        loginB.setForeground(new java.awt.Color(255, 255, 255));
        loginB.setText("Log in");
        loginB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginB.setBorderPainted(false);
        loginB.setFocusable(false);
        loginB.setName(""); // NOI18N
        loginB.setOpaque(true);

        existAccLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        existAccLabel.setText("Log in to existing account.");

        javax.swing.GroupLayout loginPLayout = new javax.swing.GroupLayout(loginP);
        loginP.setLayout(loginPLayout);
        loginPLayout.setHorizontalGroup(
            loginPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(loginPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userEmailLabel)
                    .addComponent(userPwdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPLayout.createSequentialGroup()
                        .addComponent(showPwd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(keepSigned))
                    .addComponent(userEmail)
                    .addComponent(userPwd, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loginPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPLayout.createSequentialGroup()
                        .addComponent(loginB, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPLayout.createSequentialGroup()
                        .addComponent(loginLabel)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPLayout.createSequentialGroup()
                        .addComponent(existAccLabel)
                        .addGap(103, 103, 103))))
        );
        loginPLayout.setVerticalGroup(
            loginPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(loginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(existAccLabel)
                .addGap(49, 49, 49)
                .addGroup(loginPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userEmailLabel)
                    .addComponent(userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(loginPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userPwdLabel)
                    .addComponent(userPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(loginPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showPwd)
                    .addComponent(keepSigned))
                .addGap(51, 51, 51)
                .addComponent(loginB, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPLayout = new javax.swing.GroupLayout(mainP);
        mainP.setLayout(mainPLayout);
        mainPLayout.setHorizontalGroup(
            mainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPLayout.createSequentialGroup()
                .addGroup(mainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loginP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registrationP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPLayout.createSequentialGroup()
                        .addGroup(mainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPLayout.createSequentialGroup()
                                .addGap(294, 294, 294)
                                .addComponent(logoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPLayout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(infoLabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPLayout.setVerticalGroup(
            mainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registrationP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLabel)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userEmailActionPerformed

    private void showPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showPwdActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void lNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameActionPerformed

    private void signupBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signupBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField condpwd;
    private javax.swing.JLabel confpwdLabel;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel existAccLabel;
    private javax.swing.JTextField fName;
    private javax.swing.JLabel fNameLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JCheckBox keepSigned;
    private javax.swing.JTextField lName;
    private javax.swing.JLabel lNameLabel;
    private javax.swing.JButton loginB;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginP;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel logoP;
    private javax.swing.JPanel mainP;
    private javax.swing.JLabel newAccLabel;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel registrationP;
    private javax.swing.JCheckBox showPwd;
    private javax.swing.JButton signupB;
    private javax.swing.JLabel singpLabel;
    private javax.swing.JCheckBox termsCond;
    private javax.swing.JLabel trafficDataLabel;
    private javax.swing.JLabel unameLabel;
    private javax.swing.JTextField userEmail;
    private javax.swing.JLabel userEmailLabel;
    private javax.swing.JPasswordField userPwd;
    private javax.swing.JLabel userPwdLabel;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
